# Generated by Django 5.0.3 on 2024-04-07 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.announcement')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.content')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.ManyToManyField(through='myapp.AnnouncementContent', to='myapp.content'),
        ),
    ]
