# Generated by Django 5.0.3 on 2024-04-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_content_announcementcontent_announcement_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementcontent',
            old_name='post',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='announcementcontent',
            old_name='foto',
            new_name='content',
        ),
    ]
